#!/usr/bin/env python3
"""Convert a Colab `.py` export back into a `.ipynb` you can upload and run.

Why not jupytext: jupytext reads *percent-format* python, where a magic cell keeps its magic
and is marked by `# %%`. Colab's exporter does something else — it comments the magic cell out
entirely:

    # Commented out IPython magic to ensure Python compatibility.
    # %%bash
    # apt-get install ...

so `%%bash` / `%%writefile` never execute if you just uncomment the file. It also flattens
both markdown cells into bare triple-quoted strings, and separates plain code cells with a
SINGLE blank line — indistinguishable from a blank line inside a cell, so cell boundaries
are not recoverable in general.

So this tool anchors boundaries on the only three signals the export makes unambiguous (the
magic sentinel, the markdown docstrings, and the `# ----` stage banners) and then PROVES the
conversion is lossless: every magic cell is re-commented and spliced back between the
original line spans, and that must reproduce the input exactly. A clean diff means nothing
was dropped or invented, whatever the boundaries turned out to be. Blank lines *inside* a
commented cell are `# ` (hash + space); the separator between cells is a real blank line.

Usage:
    python colab_export_to_ipynb.py script.py [-o out.ipynb]
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

import nbformat

SENTINEL = "# Commented out IPython magic to ensure Python compatibility."
BANNER = re.compile(r"^# (-{5,}|# -{5,})\s*$")
CODING = "# -*- coding: utf-8 -*-"
MAGIC_LINE = re.compile(r"^# (%%\w+.*)$")
QUOTE = '"' * 3
# Colab stamps its own provenance into the first markdown cell. That is export metadata, not
# content, so it is stripped from the emitted notebook (but kept for the lossless diff).
BOILERPLATE = re.compile(
    r"\A[^\n]*\.ipynb\n\nAutomatically generated by Colab\.\n\n"
    r"Original file is located at\n[ \t]*\S+\n\n"
)


def uncomment(line: str) -> str:
    return line[2:] if line.startswith("# ") else ""


def recomment(line: str) -> str:
    return "# " + line


def find_starts(lines: list[str], base: int) -> list[int]:
    """Index of the first line of every cell."""
    def close(j: int) -> int:
        return next(k for k in range(j + 1, len(lines)) if lines[k].rstrip().endswith(QUOTE))

    starts: list[int] = []
    plain = False        # True once a plain code run is open
    banners = 0          # a cell header is exactly two banners, so the 3rd opens a new cell
    i = base
    while i < len(lines):
        line = lines[i]
        if line == SENTINEL:
            starts.append(i)
            i += 2
            while i < len(lines) and lines[i].startswith("#"):
                i += 1
            plain, banners = False, 0
            continue
        if line.startswith(QUOTE):
            starts.append(i)
            i = close(i) + 1
            plain, banners = False, 0
            continue
        if not line.strip():
            i += 1
            continue
        if BANNER.match(line):
            if plain and banners >= 2:
                starts.append(i)
                banners = 1
            else:
                banners += 1
                if not plain:
                    starts.append(i)
                    plain = True
            i += 1
            continue
        if not plain:
            starts.append(i)
            plain = True
        i += 1
    return starts


def parse(text: str) -> tuple[list[dict], list[str], bool]:
    lines = text.splitlines()
    coding = bool(lines) and lines[0] == CODING
    base = 1 if coding else 0
    starts = find_starts(lines, base)
    cells = []
    for k, s in enumerate(starts):
        e = starts[k + 1] if k + 1 < len(starts) else len(lines)
        span = lines[s:e]
        if span[0] == SENTINEL:
            magic = MAGIC_LINE.match(span[1])
            if not magic:
                raise SystemExit(f"line {s + 2}: magic cell with no magic line: {span[1]!r}")
            body = [uncomment(l) for l in span[2:] if l.startswith("#")]
            cells.append({"kind": "code", "magic": True, "start": s, "span": span,
                          "body": body,
                          "source": "\n".join([magic.group(1)] + body)})
        elif span[0].startswith(QUOTE):
            # Colab opens the block with `"""<first content line>`, so the content starts
            # *after* the delimiter on that line -- dropping the whole line loses a line.
            close = next(j for j in range(s + 1, e) if span[j - s].rstrip().endswith(QUOTE))
            cells.append({"kind": "markdown", "magic": False, "start": s, "span": span,
                          "source": "\n".join([span[0][len(QUOTE):]] + span[1:close])})
        else:
            body = list(span)
            while body and not body[0].strip():
                body.pop(0)
            while body and not body[-1].strip():
                body.pop()
            cells.append({"kind": "code", "magic": False, "start": s, "span": span,
                          "source": "\n".join(body)})
    return cells, lines, coding


def render(cells: list[dict], lines: list[str], base: int, coding: bool) -> str:
    """Rebuild Colab's export format. Must equal the input for the diff check to pass.

    Only the commented magic bodies are rewritten; every other line, including the blank
    separators and the cell trailing, is replayed verbatim.
    """
    out: list[str] = [CODING] if coding else []
    cursor = base
    for c in cells:
        out += lines[cursor:c["start"]]
        if c["magic"]:
            body = c["body"]
            out.append(SENTINEL)
            out.append("# " + c["source"].split("\n")[0])
            out += [recomment(l) for l in body[:-1]]
            # Colab emits a bare '#' for a cell whose source ends with a newline.
            out.append(recomment(body[-1]).rstrip() if body[-1] == "" else recomment(body[-1]))
            out += c["span"][2 + len(body):]        # blank separator, verbatim
        else:
            out += c["span"]
        cursor = c["start"] + len(c["span"])
    out += lines[cursor:]
    return "\n".join(out).rstrip("\n")


def to_python(source: str) -> str:
    """Neutralise IPython line escapes (`!cmd`, `%magic`) so `compile()` can be used."""
    out = []
    for line in source.split("\n"):
        stripped = line.lstrip()
        out.append(line[: len(line) - len(stripped)] + "pass"
                   if stripped.startswith(("!", "%")) else line)
    return "\n".join(out)


def to_notebook(cells: list[dict], name: str) -> nbformat.NotebookNode:
    nb = nbformat.v4.new_notebook()
    nb.metadata["colab"] = {"name": name, "provenance": [], "toc_visible": True}
    for c in cells:
        if c["kind"] == "markdown":
            nb.cells.append(
                nbformat.v4.new_markdown_cell(BOILERPLATE.sub("", c["source"], count=1)))
        else:
            nb.cells.append(nbformat.v4.new_code_cell(c["source"]))
    return nb


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("src", type=Path)
    ap.add_argument("-o", "--out", type=Path)
    args = ap.parse_args()

    text = args.src.read_text(encoding="utf-8")
    cells, lines, coding = parse(text)

    base = 1 if coding else 0
    rebuilt = render(cells, lines, base, coding)
    if rebuilt.splitlines() != text.splitlines():
        diff = list(difflib.unified_diff(text.splitlines(), rebuilt.splitlines(),
                                         "input", "rebuilt", lineterm="", n=1))
        print("FAIL: conversion is lossy\n" + "\n".join(diff[:40]))
        return 1

    for n, c in enumerate(cells):
        if c["kind"] != "code":
            continue
        head = c["source"].split("\n", 1)[0]
        if head.startswith("%%writefile "):
            payload = c["source"].split("\n", 1)[1]
            if head.endswith(".py"):
                try:
                    compile(payload, head[len("%%writefile "):], "exec")
                except SyntaxError as e:
                    print(f"FAIL: cell {n} writes invalid python: {e.msg} (line {e.lineno})")
                    return 1
        elif not head.startswith("%%"):
            try:
                compile(to_python(c["source"]), f"cell{n}", "exec")
            except SyntaxError as e:
                print(f"FAIL: cell {n} does not compile: {e.msg} (line {e.lineno})")
                return 1

    out = args.out or args.src.with_suffix(".ipynb")
    nb = to_notebook(cells, out.name)
    for n, c in enumerate(nb.cells):
        if c.cell_type == "markdown" and "Automatically generated by Colab" in c.source:
            print(f"FAIL: cell {n} still carries Colab's export boilerplate")
            return 1
    nbformat.validate(nb)
    nbformat.write(nb, str(out))

    md = sum(1 for c in cells if c["kind"] == "markdown")
    mag = sum(1 for c in cells if c["magic"])
    print(f"OK: {len(cells)} cells ({md} markdown, {len(cells) - md} code, {mag} magic), "
          f"lossless round-trip -> {out}")
    for n, c in enumerate(cells):
        head = (c["source"].splitlines() or [""])[0]
        tag = "md  " if c["kind"] == "markdown" else ("MAGIC" if c["magic"] else "code")
        print(f"  {n:2d} {tag:5} {head[:64]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
